sudo: false

language: node_js

os:
  - windows
  - linux
  - osx

node_js:
  - "8"
  - "9"
  - "10"
  - "11"
  - "12"

install_windows:
  # Install dependencies and build
  - npm install

install_linux:
  - PATH="`npm bin`:`npm bin -g`:$PATH"
  # Install dependencies and build
  - npm install

install_osx:
  - PATH="`npm bin`:`npm bin -g`:$PATH"
  # Install dependencies and build
  - npm install

script:
  # Output useful info for debugging
  - node --version
  - npm --version
  # Run tests
  - npm test
